=== Aakashdarsi/Algorithms-All-Sets/a.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT aliens (alien+)>
<!ELEMENT alien (name,Age,Gender)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ATTLIST alien aid ID #REQUIRED>
<!ATTLIST alien lang (p|Java|C|CPP|GOLANG) "p">

=== Aakashdarsi/Algorithms-All-Sets/a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aliens SYSTEM "a.dtd">

<aliens>
    <alien aid = "tt" lang = "p">
        <name>Aakash Darsi</name>
        <Age>20</Age>

        <Gender>Male</Gender>       
    </alien>
    
    <alien aid = "pp" lang="C"> 
        <name>Bharani</name>
        <Age>22</Age>


        <Gender>Male</Gender>
    </alien>

</aliens>
